#!/usr/bin/env node
/**
 * Seed Setup — generates wallet seed with one-time human-readable backup.
 *
 * Usage:
 *   node scripts/seed-setup.mjs [--backup /path/to/backup.txt] [--env /path/to/.env]
 *
 * This script:
 * 1. Generates a 12-word BIP39 mnemonic via WDK.getRandomSeedPhrase()
 * 2. Writes WALLET_SEED to .env (read by wallet-isolate at startup)
 * 3. Creates a human-readable backup file with the mnemonic
 * 4. Schedules auto-delete of backup file (background process, 10 min)
 *
 * Uses WDK's own entropy (sodium-based) — no custom crypto.
 *
 * @security This script handles seed material. It runs ONCE during setup,
 * NOT during normal operation. The agent should NOT read the backup file.
 * Output to stdout is machine-readable JSON (no seed material).
 */

import { writeFileSync, readFileSync, existsSync, chmodSync } from 'node:fs';
import { execSync } from 'node:child_process';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const projectRoot = resolve(__dirname, '..');

// Parse args
const args = process.argv.slice(2);
const getArg = (name) => {
  const idx = args.indexOf(name);
  return idx !== -1 && args[idx + 1] ? args[idx + 1] : null;
};

const backupPath = getArg('--backup') || resolve(projectRoot, '.oikos-seed-backup.txt');
const envPath = getArg('--env') || resolve(projectRoot, '.env');
const autoDeleteMin = parseInt(getArg('--auto-delete') || '10', 10);
const agentName = getArg('--name') || 'Oikos-Agent';

// Check if seed already exists in .env
if (existsSync(envPath)) {
  const envContent = readFileSync(envPath, 'utf-8');
  const seedMatch = envContent.match(/^WALLET_SEED="?([^"\n]+)"?/m);
  if (seedMatch && seedMatch[1] && !seedMatch[1].includes('abandon')) {
    process.stderr.write(`[seed-setup] Seed already exists in ${envPath}\n`);
    process.stdout.write(JSON.stringify({ status: 'exists', envPath }));
    process.exit(0);
  }
}

// Generate 24-word seed using WDK's own BIP39 (256-bit entropy, per CLAUDE.md rules)
// Note: WDK.getRandomSeedPhrase() wrapper in beta.5 doesn't forward the wordCount arg,
// so we call WalletManager.getRandomSeedPhrase(24) directly from @tetherto/wdk-wallet.
const wdkWallet = await import('@tetherto/wdk-wallet');
const WalletManager = wdkWallet.default;
const mnemonic = WalletManager.getRandomSeedPhrase(24);
const words = mnemonic.split(' ');

// Write or update .env
let envContent = '';
if (existsSync(envPath)) {
  envContent = readFileSync(envPath, 'utf-8');
  // Replace placeholder seed
  envContent = envContent.replace(
    /^WALLET_SEED="?[^"\n]*"?/m,
    `WALLET_SEED="${mnemonic}"`
  );
} else {
  envContent = `# Oikos Protocol — Generated by seed-setup.mjs
# ${new Date().toISOString()}
OIKOS_MODE="testnet"
WALLET_SEED="${mnemonic}"
MOCK_WALLET="false"
MOCK_SWARM="false"
SWARM_ENABLED="true"
AGENT_NAME="${agentName}"
AGENT_CAPABILITIES="payment,swap,bridge,yield,analysis,price-feed"
DASHBOARD_PORT="3420"
DASHBOARD_HOST="0.0.0.0"
WALLET_RUNTIME="node"
WALLET_ISOLATE_PATH="./wallet-isolate/dist/src/main.js"
POLICY_FILE="policies.json"
AUDIT_LOG_PATH="audit.jsonl"
ETH_RPC_URL="https://rpc.sepolia.org"
BTC_NETWORK="testnet"
`;
}

writeFileSync(envPath, envContent);
try { chmodSync(envPath, 0o600); } catch { /* non-critical */ }

// Write human-readable backup file
const lines = [];
for (let i = 0; i < words.length; i += 4) {
  lines.push(
    words.slice(i, i + 4)
      .map((w, j) => `  ${String(i + j + 1).padStart(2)}. ${w.padEnd(12)}`)
      .join('')
  );
}

const backup = `
╔═══════════════════════════════════════════════════════════════╗
║                  OIKOS WALLET — SEED BACKUP                   ║
║                                                               ║
║  Write these words on paper. Store them safely.               ║
║  Anyone with these words can control your funds.              ║
╚═══════════════════════════════════════════════════════════════╝

${lines.join('\n')}

  Agent: ${agentName}
  Created: ${new Date().toISOString()}

  ⚠️  DELETE THIS FILE AFTER SAVING THE WORDS
  ⚠️  DO NOT SHARE WITH ANYONE — NOT EVEN YOUR AI AGENT
  ⚠️  THIS FILE AUTO-DELETES IN ${autoDeleteMin} MINUTES

╔═══════════════════════════════════════════════════════════════╗
║  To recover this wallet on a new machine:                     ║
║  Set WALLET_SEED="<your 24 words>" in .env                    ║
║  Then start Oikos normally.                                   ║
╚═══════════════════════════════════════════════════════════════╝
`.trimStart();

writeFileSync(backupPath, backup);
try { chmodSync(backupPath, 0o600); } catch { /* non-critical */ }

// Schedule auto-delete of backup file (background process)
try {
  execSync(`(sleep ${autoDeleteMin * 60} && rm -f "${backupPath}") &`, { shell: '/bin/bash' });
} catch { /* non-critical on systems without bash */ }

// Output machine-readable status (NO seed material!)
process.stdout.write(JSON.stringify({
  status: 'created',
  backupFile: backupPath,
  envFile: envPath,
  autoDeleteMinutes: autoDeleteMin,
  wordCount: words.length,
  agentName,
}) + '\n');

process.stderr.write(`[seed-setup] Seed generated (${words.length} words)\n`);
process.stderr.write(`[seed-setup] Backup written to ${backupPath}\n`);
process.stderr.write(`[seed-setup] Auto-delete in ${autoDeleteMin} minutes\n`);
